---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(linmod)
library(bench)
library(kableExtra)
```

To run a simple linear regression with `linear_model`:

```{r}
linear_model(Y = mtcars[ , "mpg"], X = mtcars[ , "hp"])
```

`linear_model` coefficients match those from `lm`:

```{r}
all.equal(as.numeric(unlist(lm(mtcars[, "mpg"] ~ mtcars[, "hp"])[["coefficients"]])),
          linear_model(Y = mtcars[, "mpg"], X = mtcars[, "hp"])[[1]][["Estimates"]])
```

Compare run time of `linear_model` to that of `lm`:

```{r}
result <- bench::mark(as.numeric(unlist(lm(mtcars[, "mpg"] ~ mtcars[,"hp"])[["coefficients"]])),
                      as.numeric(linear_model(Y = mtcars[, "mpg"], mtcars[, "hp"])[[1]][["Estimates"]]))
```

View table of result:

```{r}
print(result,n=Inf)
```

Compare summary output of `lm` with output of `linear_model`:

```{r}
summary(lm(mtcars[,"mpg"]~.,data=mtcars[,2:11]))
```

```{r}
linear_model(Y = mtcars[ , "mpg"], X=as.matrix(mtcars[,2:11]))
```

